pipeline:
  api-test:
    image: node:14.17-alpine
    commands:
      - apk update && apk upgrade
      - node -v
      - cd api/
      - npm ci
      - npm run ci-test-token
      - npm run ci-test-token-enterprise
      - npm run ci-test-native

  watcher-test:
    image: node:14.17-alpine
    commands:
      - apk update && apk upgrade
      - node -v
      - cd watcher/
      - npm ci
      - npm run ci-test-token
      - npm run ci-test-token-enterprise
      - npm run ci-test-native

  api-publish:
    image: plugins/docker
    dockerfile: Dockerfile.api
    repo: iexechub/iexec-market-api
    secrets: [docker_username, docker_password]
    auto_tag: true
    when:
      ref:
        include: refs/tags/v[1-9]*.*[0-9].*[0-9]
        exclude: refs/tags/v[1-9]*.*[0-9].*[0-9]-*

  watcher-publish:
    image: plugins/docker
    dockerfile: Dockerfile.watcher
    repo: iexechub/iexec-market-watcher
    secrets: [docker_username, docker_password]
    auto_tag: true
    when:
      ref:
        include: refs/tags/v[1-9]*.*[0-9].*[0-9]
        exclude: refs/tags/v[1-9]*.*[0-9].*[0-9]-*

  api-publish-alpha:
    image: plugins/docker
    dockerfile: Dockerfile.api
    repo: iexechub/iexec-market-api
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_TAG##v}
    when:
      ref: refs/tags/v[1-9]*.*[0-9].*[0-9]-alpha.*[0-9]

  watcher-publish-alpha:
    image: plugins/docker
    dockerfile: Dockerfile.watcher
    repo: iexechub/iexec-market-watcher
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_TAG##v}
    when:
      ref: refs/tags/v[1-9]*.*[0-9].*[0-9]-alpha.*[0-9]

services:
  chain-token:
    image: iexechub/poco-chaintest:5.3.0-token-parity
    pull: true
  chain-native:
    image: iexechub/poco-chaintest:5.3.0-native-parity
    pull: true
  mongo:
    image: mongo:latest
    pull: true
  redis:
    image: redis:alpine
    pull: true
