pipeline:
  api-test:
    image: node:14.6-alpine
    commands:
      - apk update && apk upgrade
      - node -v
      - cd api/
      - npm i
      - npm run ci-test-token
      - npm run ci-test-token-enterprise
      - npm run ci-test-native

  watcher-test:
    image: node:14.6-alpine
    commands:
      - apk update && apk upgrade
      - node -v
      - cd watcher/
      - npm i
      - npm run ci-test-token
      - npm run ci-test-native

  api-publish:
    image: plugins/docker
    dockerfile: Dockerfile.api
    repo: iexechub/iexec-market-api
    secrets: [docker_username, docker_password]
    auto_tag: true
    when:
      ref: [refs/tags/v5*]

  watcher-publish:
    image: plugins/docker
    dockerfile: Dockerfile.watcher
    repo: iexechub/iexec-market-watcher
    secrets: [docker_username, docker_password]
    auto_tag: true
    when:
      ref: [refs/tags/v5*]

services:
  chain-token:
    image: iexechub/poco-chaintest:5.3.0-alpha.1-token-parity
    pull: true
  chain-native:
    image: iexechub/poco-chaintest:5.3.0-alpha.1-native-parity
    pull: true
  mongo:
    image: mongo:latest
    pull: true
  redis:
    image: redis:alpine
    pull: true
